GIT_URL=https://github.com/devashishcodes/assignment-6-ansible-app.git
GIT_BRANCH=main

SLACK_CHANNEL_NAME=build-status
ENVIRONMENT=prod
CODE_BASE_PATH=env/prod
ACTION_MESSAGE=Deployment completed successfully
KEEP_APPROVAL_STAGE=true
